### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by gevro** [PacificBiosciences/HiFi-human-WGS-WDL#167] opened 2024-11-16 06:04 UTC
Hi, I think the output documentation is missing these:

humanwgs_family
joint_trgt_vcf
File
humanwgs_family
joint_trgt_vcf_index
File

**Comment by williamrowell** [comment] 2024-11-16 06:13
This is not a bug, but an omission in the documentation.  Thanks for pointing it out.  I'll update in the next release.

These are, exactly as they sound, merged tandem repeat variant calls produced by [`trgt merge`](https://github.com/PacificBiosciences/trgt/blob/main/docs/cli.md#merge-command-line).

**Comment by gevro** [comment] 2024-11-16 06:15
Ok. A few other outputs are also missing and some are misnamed (missing tertiary_).

**Closed** 2024-11-16 22:02 UTC
